modLoader="javafml"
loaderVersion="[35,)"
license="Creative Commons"

[[mods]]
modId="glasscraftery"
version="1.0.0"
displayName="Glass Craftery"
credits="Thanks to Avalon Team and my Twitter Followers." 
authors="Avalon Team.""
description='''
A sister mod to Better CLay, it adds more glassy-like blocks.
'''